---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74/hugo_0.74_Linux-64bit.deb
  - sudo dpkg -i hugo_0.74_Linux-64bit.deb
script:
  - hugo
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
