baseURL = "https://sampathdechu.github.io/"
languageCode = "en-us"
title = "Sampath Dechu"
theme = "xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2   
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 4
[[menu.main]]
    name = "Patents"
    url = "/Patents/"
    weight = 5 
[[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 6
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 7


[params]
    header = "I am header"
    footer = "sampath.dechu-at-gmail-dot-com | [Linkedin](https://in.linkedin.com/in/sampathdechu) | [Github](https://github.com/sampathdechu) | [Twitter](https://twitter.com/sampathdechu)  "


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
