baseURL = "https://sampathdechu.github.io/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

[params]
    description = "A website built using [this](https://github.com/yihui/hugo-xmin) theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
